import type { Metadata } from "next";
import { Carrois_Gothic, Inter } from "next/font/google";
import "@/styles/globals.css";
import Footer from "@/components/Footer";
import SideNav from "@/components/SideNav";
import { validateRequest } from "@/lib/db";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { session } = await validateRequest();

	if (!session) {
		redirect("/");
	}

	return (
		<html lang="en">
			<body className={inter.className}>
				<SideNav />
				<main className="sm:ml-[18rem]">{children}</main>
			</body>
		</html>
	);
}
